// src/frontend-svelte/src/routes/navbar.svelte
<script lang="ts">
	import { page } from '$app/stores';
	import ColorToggle from './colorToggle.svelte';

	const links = [
		{
			name: 'Home',
			url: '/'
		},
		// {
		//   name: 'About',  // about page does not exist currently
		//   url: '/about'
		// },
		{
			name: 'Login',
			url: '/auth/login'
		},
		{
			name: 'Signup',
			url: '/auth/signup'
		},
		{
			name: 'Dashboard',
			url: '/dashboard'
		}
	];

	let display: {
		name: string;
		url: string;
	}[];

	$: {
		display = links.filter((i) => {
			// if (["/auth/login", "/auth/signup"].includes(i.url) /* && ctx.loggedIn */) {
			// 	return false;
			// } else if (i.url === "/dashboard" /* && !ctx.loggedIn */) {
			// 	return false;
			// }
			console.log($page.url.pathname.toLowerCase());
			return (i.url !== $page.url.pathname.toLowerCase());
		})
	}
</script>

<header>
	<a class="nav-title" href="/">Rectilearn</a>

	<div class="ml-auto">
		<div class="flex gap-4 md:gap-9 font-semibold">
			<ColorToggle class="appearance-none px-3 py-2 rounded-md font-bold text-gray-600 dark:text-inherit hover:no-underline hover:bg-blue-300 hover:dark:bg-gray-700" />
			{#each display as link}
				<a href={link.url} class="px-3 py-2 rounded-md font-bold text-gray-600 dark:text-inherit hover:no-underline hover:bg-blue-300 hover:dark:bg-gray-700">{link.name}</a>
			<!-- <a href="/auth/signup" class="hover-underline">Signup</a> -->
			{/each}
		</div>
	</div>
</header>

<style lang="scss">
	header {
		@apply flex items-center z-[10000] dark:shadow-neutral-800 
               shadow-sm px-8 h-[var(--navbar-height)] max-h-[var(--navbar-height)]
			   bg-black/[.05] dark:bg-black/[.5];
	}

	.nav-title {
		@apply font-pacifico text-xl;
	}
</style>

// apps/frontend-next/components/Home/navBar.tsx
"use client";

import { ReactNode, useContext } from 'react';
import {
  Box,
  Flex,
  HStack,
  useDisclosure,
  useColorModeValue,
  useColorMode,
  Stack,
  IconButton
} from '@chakra-ui/react';
import "@fontsource/pacifico";
import { Link } from '@chakra-ui/next-js';
import { HamburgerIcon, CloseIcon } from '@chakra-ui/icons';
import {
  FiSun,
  FiMoon,
} from "react-icons/fi";
import { usePathname } from 'next/navigation';
import AuthCtx from '@/lib/auth';

const links = [
  {
    name: 'Home',
    url: '/'
  },
  // {
  //   name: 'About',  // about page does not exist currently
  //   url: '/about'
  // },
  {
    name: 'Login',
    url: '/login'
  },
  {
    name: 'Signup',
    url: '/signup'
  },
  {
    name: 'Dashboard',
    url: '/dashboard'
  }
];

const NavLink = ({ children, href }: { children: ReactNode, href: string }) => (
  <Link
    href={href}
    px={3}
    py={2}
    rounded={'md'}
    fontWeight={"bold"}
    color={useColorModeValue('gray.600', undefined)}
    _hover={{
      textDecoration: 'none',
      bg: useColorModeValue('blue.100', 'gray.700'),
    }}
  >
    {children}
  </Link>
);

export default function NavBar() {
  const { isOpen, onOpen, onClose } = useDisclosure();
  const { toggleColorMode } = useColorMode();
  const pathname = usePathname();
  const ctx = useContext(AuthCtx);
  const Links = links.filter((i) => {
    if (["/login", "/signup"].includes(i.url) && ctx.loggedIn) {
      return false;
    } else if (i.url === "/dashboard" && !ctx.loggedIn) {
      return false;
    }
    return (i.url !== pathname.toLowerCase())
  });
  return (
    <>
      <Box bg={useColorModeValue('rgba(0, 0, 0, 0.05)', 'rgba(0, 0, 0, 0.5)')} px={4}>
        <Flex h={16} alignItems={'center'} justifyContent={'space-between'}>
            <Box fontFamily={"pacifico"}>
              <Link href={"/"}>Rectilearn</Link>
            </Box>
            <HStack
              as={'nav'}
              spacing={4}
              display={{ base: 'none', md: 'flex' }}
            >
              <IconButton
                size="lg"
                variant="ghost"
                aria-label="toggle theme"
                icon={useColorModeValue(<FiSun />, <FiMoon />)}
                onClick={toggleColorMode}
                _hover={{
                  bg: useColorModeValue('blue.100', 'gray.700')
                }}
              />
              {Links.map((link, index) => (
                <NavLink key={index} href={link.url}>{link.name}</NavLink>
              ))}
            </HStack>
            <HStack
              as={'nav'}
              spacing={4}
              display={{ base: 'flex', md: 'none' }}
            >
              <IconButton
                size={'md'}
                variant="ghost"
                aria-label="toggle theme"
                icon={useColorModeValue(<FiSun />, <FiMoon />)}
                bg={useColorModeValue('blue.100', 'gray.700')}
                onClick={toggleColorMode}
              />
              <IconButton
                size={'md'}
                icon={isOpen ? <CloseIcon /> : <HamburgerIcon />}
                aria-label={'Open Menu'}
                display={{ md: 'none' }}
                onClick={isOpen ? onClose : onOpen}
              />
            </HStack>
        </Flex>

        {isOpen && (
          <Box pb={4} display={{ md: 'none' }}>
            <Stack as={'nav'} spacing={4}>
              {Links.map((link, index) => (
                <NavLink key={index} href={link.url}>{link.name}</NavLink>
              ))}
            </Stack>
          </Box>
        )}
      </Box>
    </>
  );
}
